-- 1. Limpieza segura: Borrar la tabla si ya existe
DROP TABLE IF EXISTS item;

-- 2. Creación de la tabla con la sintaxis correcta de Clave Primaria Compuesta
CREATE TABLE item (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      sku VARCHAR(255) NOT NULL,
                      quantity INT NOT NULL,
                      store_id VARCHAR(255) NOT NULL,

    -- Restricción de negocio: (sku, store_id) debe ser único
                      UNIQUE (sku, store_id)
);

-- 3. Carga de datos iniciales
INSERT INTO item (sku, quantity, store_id) VALUES ('A101', 10, 'STORE_A');
INSERT INTO item (sku, quantity, store_id) VALUES ('B202', 5, 'STORE_A');
INSERT INTO item (sku, quantity, store_id) VALUES ('A101', 15, 'STORE_B');