#spring:
#  application:
#    name: ims-gateway
#  r2dbc:
#    url: r2dbc:h2:mem:///gatewaydb;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            # RUTA 0: HACIA EL BACKEND (ims-back) - CON RATE LIMITER
#            - id: ims-back
#              uri: http://localhost:9090
#              predicates:
#                - Path=/api/inventory/**
#              filters:
#                - StripPrefix=2
#                - name: RequestRateLimiter
#
#            - id: ims-front
#              uri: http://localhost:9091
#              predicates:
#                - Path=/ui/**
#              filters:
#                - StripPrefix=2
#
#server:
#  port: 9092
#
#management:
#  health:
#    redis:
#      enabled: false
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG